name: skgl_flutter
description: A flutter plugin to generate & validate human readable, 20-character serial keys with up to 8 features embedded.
version: 1.0.0
homepage: https://github.com/chayanforyou/skgl_flutter

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter: